### PR TITLE
Building a Web Scraping Extension with Playwright

### PR DESCRIPTION
**Pull request by Okeke12nancy**
Webscraping Directus Extension

### CODE REVIEW

**Comment by phazonoverload** [comment]
We were specifically talking about using Playwright - what happened to that?

**Comment by Okeke12nancy** [comment]
I used playwright initially, but the data it was scraping was not in the right structure, so that's why I decided not to use it.

**Comment by phazonoverload** [comment]
I can only accept this post if it's using Playwright - spinning up a headless browser that can perform interactions is at the core of why this concept was interesting. 

Let me know how you wish to proceed. I can review this post with a revised scope of being Cheerio related but will have to reduce the budget to $350, or you can build with Playwright (I would expect to see some configuration for automating user interaction in order to access data) with the original budget.

**Comment by Okeke12nancy** [comment]
I will use playwright. Let me do more research on it. Thank you

**Comment by phazonoverload** [comment]
Ok - if we said a week from today to update the draft, would that be viable? That's Thurs 18 July?

**Comment by Okeke12nancy** [comment]
Sure

**Comment by Okeke12nancy** [comment]
Hello @phazonoverload , i have added the playwright webscraping service

**Comment by Okeke12nancy** [comment]
Hello @phazonoverload , I am yet to get feedback from you based on my draft

**Comment by phazonoverload** [comment]
I'd scheduled time based on the original due date. I was out of office all last week and will get to it in the next day or so.

**Comment by phazonoverload** [comment]
Thank you for writing this, and we are happy to consider it done in it's current state. There are some edits required which my team will do when we have time, so I can't offer an estimate timeline for publishing. 

This repo is just for authoring/reviewing - the actual piece will be published via a Directus project, so we'll take it from here. I'll close this issue to keep the main branch clean, but this is a acceptance of your work.

Could you email us at [devrel@directus.io](mailto:devrel@directus.io) and we'll share what we need to get you paid. Thanks!

**Pull request closed without merging**
